export const FETCH_PLAYERS_PENDING = 'FETCH_PLAYERS_PENDING';
export const FETCH_PLAYERS_FULFILLED = 'FETCH_PLAYERS_FULFILLED';
export const FETCH_PLAYERS_REJECTED = 'FETCH_PLAYERS_REJECTED';
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const GET_TERM = 'GET_TERM';
