export const FETCH_PLAYERS_REQUEST = 'FETCH_PLAYERS_REQUEST';
export const FETCH_PLAYERS_SUCCESSFUL = 'FETCH_PLAYERS_SUCCESSFUL';
export const FETCH_PLAYERS_FAILURE = 'FETCH_PLAYERS_FAILURE';
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const GET_TERM = 'GET_TERM';
